name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Client project setup
      run: cd app && npm install && npm run release && cd ..
    - name: Client unit tests
      run: cd app && npm run test && cd ..
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run xUnit tests
      run: dotnet test
      env : 
        MYSQL_DB : ${{ secrets.MYSQL_DB }}

